---
title: "Fair Market Rent Difference: A Pattern Analysis of Unfair Housing Prices"
format:
  arxiv-pdf:
    keep-tex: true  
    linenumbers: false
    doublespacing: false
    runninghead: "A Preprint"
  arxiv-html: default
author:
  - name: Dylan Michaels
    affiliations:
      - name: Texas A&M University 
        department: Statistics
        address: 1 400 Bizzell St
        city: College Station, TX
        country: USA
        postal-code: 77843
    email: dmichaels54321@tamu.edu
  - name: Shouro Shuvit
    affiliations:
      - name: Texas A&M University
        department: Statistics
        address: 1 400 Bizzell St
        city: College Station, TX
        country: USA
        postal-code: 77843
    email: shouroshuvit@tamu.edu
abstract: |
  The fair market rent (FMR) system in the United States is used by the Department of Housing to ascertain what housing should cost in any given county based on economic factors, however reality often does not reflect this estimate as other factors push the cost of housing higher. Fair Market Rent Difference is an analysis technique that leverages Random Forests in order to find where in the United States there is a large difference between the FMR and the actual market rent. With Random Forests, we are able to accurately create a predictive field that shows these disparities and what areas they are formed in. The analysis will allow for a broad overlook of how housing unaffordability fluctuates with respect to space when it is compared to a price point that is based on the economic data of the county. This analysis can be a baseline for future research into market conditions that drive regions of the US to have tighter housing demands than expected by the government to then enact policy for housing affordability in unsuspecting places.

keywords: 
  - template
  - demo
bibliography: bibliography.bib  
---

# Introduction {#sec-intro}

The United States is infamous for its housing unaffordability crisis with over half of American Renters unable to afford rent according to the Joint Center for Housing Studies at Harvard University however with the government allocating 72.6 Billion dollars to be spent in 2025 for the Department of Housing and Urban Development with an additional 185 billion dollars to be spent to solve the housing crisis over the next ten years, there has to be a way to allocate the funds to maximize people being able to afford their rent. 

We believe that the Fair Market Rent system (FMR) that the government is using can be improved upon to incorporate live housing stock data to make better inferences on where in the United States housing unaffordability is. 

Currently the Fair Market Rent system relies on a multitude of factors which mainly includes economic factors like household wealth and GDP per capita within counties to find a 40th percentile price for what can be affordable housing for 60% of the population within a certain area. This system will then allocate housing units at those determined prices to push down the price of rent in those markets or allow for vouchers to be used to live in those areas. The main issue that is found is that market rent can vary wildly from year to year for reasons other than the economic well being of the community (FMR paper). 

With this research, we aim to bridge the gap between the the actual market rent and the FMR data provided by the government to portray an accurate picture of the real estate market and see what parts of the market are actually affordable 



Thesis
A metric that compares the difference between market rent and Fair Market Rent can capture more housing unaffordability data than either data set can do alone. 


# Related Works
Paper on Random forests (Breiman) overviewing method
How random forests work in general and brief overview of the randomness factor that is associated with them

Need for accounting for spatial structure (Fuss)
Impact of space on housing in general 

Paper on random forests and apartment rent (Yoshida)
Explain how breiman’s method is especially useful for apartment data because of their large sample sizes

# Methods
Used UCI Machine learning apartment dataset (cite dataset). Most data points from 2018-2019 period. Only analyzed the contiguous United States and removed some observations that were missing data. This translated to removing ~40 observations out of 52,000 Did log transform of the prices due to the heavy skewness of pricing.  Used Department of Housing’s Fair market rent data from 2019 and also log transformed the pricing. Number of bedrooms, bathrooms and the square footage of an apartment are all key in determining rent pricing. 

We use GWR as a comparison because we know rent is spatially varying (Fuss) and want a statistical model that can give us interpretable coefficients for our covariates. Through a plot of the prices it can be seen that counties near each other are similar in pricing.

We used XGboost and Random forests for their predictive power and their effectiveness in predicting rent pricing has been seen in (Yoshida). 

Compared GWR, Random Forests, and XGboost on predicting and modeling out of sample observations.

# Results
Plots with our final predictive surface are coming in the next day or two. 

Table showing that the out of sample error (MSE, RMSE, MAE) was similar across all 3 models.

Choosing Random Forest due to its predictive power.

# Discussion
Since we don’t have real results to talk about right now we can go over a brief overview of the EDA such as the coast being more unaffordable than the rest of the nation 
Discuss modeling efficiency 
How these disparities can be used to provide better policy



# Citations

This section of the template is adapted from the [Quarto citation documentation](https://quarto.org/docs/authoring/footnotes-and-citations.html).

Quarto supports bibliography files in a wide variety of formats including BibTeX and CSL. Add a bibliography to your document using the `bibliography` YAML metadata field. For example:

``` yaml
---
title: "My Document"
bibliography: references.bib
---
```

See the [Pandoc Citations](https://pandoc.org/MANUAL.html#citations) documentation for additional information on bibliography formats.

## Citation Syntax {#sec-citations}

Quarto uses the standard Pandoc markdown representation for citations. Here are some examples:

+---------------------------------------+-------------------------------------------------------------------+
| Markdown Format                       | Output                                                            |
+=======================================+===================================================================+
| ```                                   | Blah Blah [see @knuth1984, pp. 33-35; also @wickham2015, chap. 1] |
| Blah Blah [see @knuth1984, pp. 33-35; |                                                                   |
| also @wickham2015, chap. 1]           |                                                                   |
| ```                                   |                                                                   |
+---------------------------------------+-------------------------------------------------------------------+
| ```                                   | Blah Blah [@knuth1984, pp. 33-35, 38-39 and passim]               |
| Blah Blah [@knuth1984, pp. 33-35,     |                                                                   |
| 38-39 and passim]                     |                                                                   |
| ```                                   |                                                                   |
+---------------------------------------+-------------------------------------------------------------------+
| ```                                   | Blah Blah [@wickham2015; @knuth1984].                             |
| Blah Blah [@wickham2015; @knuth1984]. |                                                                   |
| ```                                   |                                                                   |
+---------------------------------------+-------------------------------------------------------------------+
| ```                                   | Wickham says blah [-@wickham2015]                                 |
| Wickham says blah [-@wickham2015]     |                                                                   |
| ```                                   |                                                                   |
+---------------------------------------+-------------------------------------------------------------------+

You can also write in-text citations, as follows:

+-------------------------------+-------------------------------+
| Markdown Format               | Output                        |
+===============================+===============================+
| ```                           | @knuth1984 says blah.         |
| @knuth1984 says blah.         |                               |
| ```                           |                               |
+-------------------------------+-------------------------------+
| ```                           | @knuth1984 [p. 33] says blah. |
| @knuth1984 [p. 33] says blah. |                               |
| ```                           |                               |
+-------------------------------+-------------------------------+

See the [Pandoc Citations](https://pandoc.org/MANUAL.html#citations) documentation for additional information on citation syntax.

To provide a custom citation stylesheet, provide a path to a CSL file using the `csl` metadata field in your document, for example:

``` yaml
---
title: "My Document"
bibliography: references.bib
csl: nature.csl
---
```

{{< pagebreak >}}

# References {.unnumbered}

::: {#refs}
:::
